### ISSUE TITLE
Add multi language support

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-mulligan-renamer#103]
As a user who does not prefer to use English, I want to be able to change the language of the plugin (well, ideally some global preference could be read) and have all strings change into my language of choice.

In order to support this, we'd need to make all strings in the app have some sort of indirection.

I propose a LocalizedString class that stores a given string in all languages. To get strings, the user would query a MulliganLocalization class that stores all strings, either as Properties or through a list of entries with IDs. IDs could be a simple enum. I'd lean toward the latter.

As far as Setting and Storage of the user's language preference, that is dependent on #206. So for now any quick solution will do. I'd add a button that pops up a simple window that allows users to set language to EditorPrefs.

**Note** that Regex operations may need to pay attention to this as well... but also maybe not because Unity doesn't support other character sets, to my knowledge.

## Example API ##

```
if(EditorGUILayout.Button(
   MulliganLocalization.GetString(
      MulliganLocalization.StringIDs.MyButton )) {}
```
And
```
MulliganLocalization.SetLanguage(
   MulliganLocalization.Language.English)
```

**Comment by edwardrowe** [comment]
See https://docs.unity3d.com/ScriptReference/PreferenceItem.html for more details on preferences.

**Comment by Mukarillo** [comment]
hey @edwardrowe,
I just created a PR (https://github.com/redbluegames/unity-mulligan-renamer/pull/208) with a simple multi-language system.

I also translated to portuguese, my native language.

To add more languages, all you have to do is clone the [english file](https://github.com/Mukarillo/unity-mulligan-renamer/blob/master/Assets/RedBlueGames/MulliganRenamer/Editor/Locale/Content/en.json), rename to something else, and translate the elements. The system will automatically gather all the *.json files inside the folder and insert the new language to the dropdown.

Hope you find this useful, I would love some feed-back :)

**Comment by edwardrowe** [comment]
Yes it looks great! I'll be so happy to have this in.

We are super busy with Sparklite but I hope I'll have time to review it sometime in the next week or two.
