### ISSUE TITLE
how to start renaming?

### ISSUE THREAD

**Issue by kisa002** [redbluegames/unity-mulligan-renamer#131]
I bought this asset and load in my project.
But I don't know how use this asset...

Can you explain for me?

p.s
I'm first time use editor asset!

**Comment by edwardrowe** [comment]
Thanks for the purchase! It sounds like I should include at least a basic overview in the Manual. Sorry for the confusion!

Check out the overview on the wiki, here:
https://github.com/redbluegames/unity-mulligan-renamer/wiki/Overview

You can bring up the tool from the menu: Window/Red Blue/Mulligan Renamer

Add the things you want to rename into the window by dragging and dropping them, or by selecting them and clicking the "Add Selected Objects" button in the menu. Then use the operations on the left hand side to configure the name changes as needed.

Let me know if there's anything else you need to know!

**Comment by edwardrowe** [comment]
No problem!
