### ISSUE TITLE
If sprite name under one texture contains changed sprite name - both sprites are changed

### ISSUE THREAD

**Issue by uvivagabond** [redbluegames/unity-mulligan-renamer#143]
![wrong changing sprites names](https://user-images.githubusercontent.com/20247639/35762372-d06a2e96-0895-11e8-8b6a-977f70a2bca3.png)

When I change **flame_1** name I  also change other sprites if their name contains **flame_1**.
(Sprites are based on same Texture).

**Comment by uvivagabond** [comment]
![reason of problem](https://user-images.githubusercontent.com/20247639/35762695-9cea7c82-089b-11e8-9cd8-5af2427433f5.png)
I searched why this happen and I founded.
I will make more tests for certainty but I think it's a reason.

**Comment by edwardrowe** [comment]
This is a good find. The regex pattern was definitely wrong but I think it's a better fix to add the "\n" to the end so that it stops searching renaming characters. I'm pushing a fix to the develop-v1.1.0 branch and I'll push out an update release after reviewing the other issues you submitted.
