### ISSUE TITLE
No final result for one operation if preview step is disable.

### ISSUE THREAD

**Issue by uvivagabond** [redbluegames/unity-mulligan-renamer#144]
![no final result](https://user-images.githubusercontent.com/20247639/35762472-78a938a8-0897-11e8-8b15-186785f72ecb.png)
If we disable Preview Steps then for one operation we don't see final result.
For 2 or more we can see final result.

**Comment by edwardrowe** [comment]
Pretty sure this is the same issue as Issue #138. Can you verify that you're only seeing this when deleting a 2nd rename operation?

**Comment by uvivagabond** [comment]
Yes, same. I checked.
