### ISSUE TITLE
Clipping name when text is bold.

### ISSUE THREAD

**Issue by uvivagabond** [redbluegames/unity-mulligan-renamer#145]
![clipped](https://user-images.githubusercontent.com/20247639/35767387-a0e264bc-08eb-11e8-8528-b27fe7f999ef.png)

When we change something in name, name is bold. Space for name is taken from not text when is not bold.

**Comment by edwardrowe** [comment]
Thanks for creating this issue. I'm not sure immediately why bold isn't being measured properly. I may end up leaving this one until I do a full rework for the GUI for speed (Issue #97).

**Comment by edwardrowe** [comment]
This should be fixed in 1.4.0. I can't reproduce it, and I reworked the way preview panel contents are calculated in that version so I think I addressed it.
