### ISSUE TITLE
Can't see deleted spaces in the Diff

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-mulligan-renamer#160]
It's hard to know when spaces are deleted because they aren't marked in the diff (can't color a space red).

To fix this, we'd need to do an improved diffing view that colored the background, similar to Sublime Text's find and replace (which looks awesome).

**Comment by Mukarillo** [comment]
Hey @edwardrowe,

I am not so sure how you imagine this working, but I tried to replicate the Sublime Text's find and replace, here is it:
<p align="center">
  <img src="https://i.imgur.com/O5jYVjo.png" alt="Example"/>
</p>
The first file is called "_[]b[][][]a" and the second "a[][]b", being [] whitespaces

It is like this that you were imagining this feature?

**Comment by edwardrowe** [comment]
It's very helpful to have another pair of eyes on this. I used SublimeText
as reference too, so it's good to hear that's where you're looking. I do
like the background highlight in SublimeText, but found it hard to
replicate. Is that what you were going for here?

This is hard to do I think within Unity, but I was hoping it would
highlight only the spaces. What do you think about that? Here's a mockup:

[image: image.png]

**Comment by Mukarillo** [comment]
I am sorry, but I can't see the attachment.
Do you mind uploading the image somewhere else and posting the link here?

**Comment by edwardrowe** [comment]
Does this work? I did that via email, must not have liked it.

![mulligan-spaces-diff-mockup](https://user-images.githubusercontent.com/398377/66725070-9bebb200-edfb-11e9-9499-6fb84faf0788.png)

**Comment by Mukarillo** [comment]
Oh, now I see, thanks!
I think I can replicate this with a bit of creativity. Let me try something.

**Comment by Mukarillo** [comment]
Hey @edwardrowe,

I think I got it working the way you imagined it
<p align="center">
  <img src="https://i.imgur.com/8g02LlX.gif" alt="Example"/>
</p>

Was that how you thought it would work?

**Comment by edwardrowe** [comment]
Yes, it looks like I envisioned, and I think your style measurement method,
to measure the areas with style.CalcSize seems solid.

Again I'll have to give you some thorough time for review later this week
or next. But thank you very much in the meantime. I don't think I'd have
tackled this for a long time but it's a really big value add!

**Comment by Mukarillo** [comment]
No problem at all @edwardrowe, take your time.
I am glad that I am adding value to this project :)
