### ISSUE TITLE
Add Package Manager Support for Mulligan

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-mulligan-renamer#205]
I *think* this is as simple as adding some files into the github repo, but I'm not sure. Do some R&D, and make it so.

**Comment by edwardrowe** [comment]
Did some research on this. Started here: https://docs.unity3d.com/Manual/CustomPackages.html
and here: https://www.youtube.com/watch?v=Bax3yCcvmfA

I think all I need is a JSON file that describes the package, but the problem is I think it needs to be in the root of the repository. And this repository is an entire Unity Project, not just the contents of the package. So I'm not sure it's possible, and I'm not sure anyone really even uses it since it's sorta buried.

Gonna defer this from the 1.7.0 release.

**Comment by Arcnor** [comment]
In case it helps, subfolders were introduced in 2019.4 and 2020.1, so at least there is that :smile: 

Initial info was at https://forum.unity.com/threads/some-feedback-on-package-manager-git-support.743345/#post-5425311 and official docs are at https://docs.unity3d.com/Manual/upm-git.html#subfolder

**Comment by edwardrowe** [comment]
Yes very helpful, thanks so much for the links!

**Comment by edwardrowe** [comment]
I've completed this and added instructions to the readme.
