### ISSUE TITLE
Regression in 1.7.0: Resizing the columns causes the cursor to flicker. Should be <-> as long as the mouse is down.

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-mulligan-renamer#218]
Fix for this is to set the cursor to the arrows while the `isSliding` is true, in addition to when it's over the divider rect.

![mulligan-slider-cursor-flicker](https://user-images.githubusercontent.com/398377/70289719-aabf6700-17a3-11ea-8f57-854458612bde.gif)

**Comment by Mukarillo** [comment]
Fixed in this [PR](https://github.com/redbluegames/unity-mulligan-renamer/pull/219)
