### ISSUE TITLE
NRE On Import in Unity 2019.3.7

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-mulligan-renamer#251]
https://forum.unity.com/threads/mulligan-renamer.532182/#post-5755693

Tried to repro but couldn't. I tried deleting all preferences in my plist, but still imported ok. I'll have to see if anyone else can repro it.

**Comment by Carwashh** [comment]
> * Was this a fresh install or an upgrade from a previous version?

It was a fresh install of the latest version on the Asset Store (I bought Mulligan on 24/04/20). 

I can't recreate the issue today. The only difference being Unity got closed over night and opened again this morning.

**Comment by edwardrowe** [comment]
Ok - it likely has something to do with some data that gets saved about the session.

Thanks again for the report!

**Comment by edwardrowe** [comment]
Did some digging into this. For me it happens 100% if the Preview window is open, but doesn't seem to have to do with any session data.

@Carwashh do you happen to use a layout where the Preferences panel is open? Maybe Docked?

**Comment by Carwashh** [comment]
Yeah I do, my layout includes:
- Game view
- Scene view
- Project
- Hierarchy
- Inspector
- Services
- Lighting
- Asset Store
- Preferences
- Project Settings
- Timeline
- Console/ Editor Console Pro

**Comment by edwardrowe** [comment]
Fixed in [release v1.7.2](https://github.com/redbluegames/unity-mulligan-renamer/releases/tag/v1.7.2). Store update to follow.
