### ISSUE TITLE
Add Spanish translations

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-mulligan-renamer#262]
Duplicate and translate the english.json file into spanish.json. I think that's all that we need to do to get this to work.

**Comment by Arcnor** [comment]
Hey, not sure why you target Spanish specifically, but I can help if you want? I didn't find any `english.json` file but a `en.json` instead, which I guess is the right one. Let me know if you want me to translate this one.

**Comment by edwardrowe** [comment]
Spanish translation help would be great!

I actually have a friend who may have nearly finished a Spanish translation, but I have to get it from him. I'll update this once I get the translation, and you could double check it in the app (he just did it by reading the json).

The file would be named es.json. These match the google language codes. I don't love it, but we should keep that convention for now.

Also, you should look at https://hacktoberfest.digitalocean.com/ if you haven't. October would be a great time to contribute this translation.

**Comment by edwardrowe** [comment]
Es.json added by @jesus-devalos. Note it's only working in the *staging* branch right now, and you could make pull requests directly in there.

There are a few keys at the bottom that were added since he made that translation. Those could be translated, and a general QA pass would be helpful. @Arcnor. No pressure, though. You've already helped just by contributing to these issues!

**Comment by Arcnor** [comment]
Awesome, I'll take a look at it soon!

Also, as a general comment, may I suggest (for next time, probably) that you change your I18N format a bit? I've seen that you have some sentences split that I guess you later concatenate in the plugin (like the "This is an example with added words" or something similar). That's a bit too English centric, and some languages won't work splitting them like that :).

Also, some languages have different words depending on the numeral appended to them, so if you have any sentences that contain a number, some languages will need the number itself to be able to translate it properly.

There are a few things like that, but I won't bore you with the details, as you might even know them already.

Anyway, I hope this helps, and if you haven't worked with I18N before this, let me know if you want any help, I love this kind of thing :).

**Comment by edwardrowe** [comment]
The advice is appreciated, for sure. I do actually know a decent amount about it through my work in games, but there is still plenty I don't know. I've never included a language that reads right to left for example. And I don't know the best way to do singular and plural stuff like "You have renamed {0} {1}" : "You have renamed 24 objects", where you might need to change the object of the sentence (1) based on the plurality of (0).

Sooo any tips on best practices or frameworks would be helpful. 

I will say most of the errors I knew about and just figured YAGNI - I'll fix it when I need it, but I should have fixed it before doing any translation.

If fixing it is feasible, we could open an issue. But I'm curious, does it actually impact Spanish or Portuguese?

**Comment by edwardrowe** [comment]
Ok this is done - feel free to review the translation @Arcnor, or let me know if the format is causing problems with any of the languages. I'm gonna close this out but feel free to comment here or we can open another issue.

**Comment by Arcnor** [comment]
Hi there, sorry for the delay, I've been busy (like everybody else :D). I've done a quick check of the translations, and unfortunately there are various issues I've found (inconsistencies, mistakes as well as things that don't make much sense). I'll try to get a corrected one this week if possible, as well as try to get some friends to do a second proofread pass on it after I'm done.

As for the format causing problems, I don't think so (at least for Spanish) but I haven't checked all sentences. Also, if you already have experience I'm sure whatever I mention will sound patronizing, so I don't want to get there :).

Thanks for this wonderful asset though, I forgot to mention it as my very first message (as well as the Null Checker, which is the one I use the most)!

**Comment by edwardrowe** [comment]
Thanks! I'm happy to contribute to open source with this Asset. If you do
have some best practices on translation formatting they'd be welcome -
especially if you have experience with it outside games. No need to worry
about sounding patronizing :)

If you want to verify the translation, I've created an issue to track the
work against:
https://github.com/redbluegames/unity-mulligan-renamer/issues/268

And if you like NotNull, I'd highly recommend checking out OdinInspector
for commercial products. It's got great (better than NotNull) validation
attributes.
