### ISSUE TITLE
Verify Spanish Translations in App

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-mulligan-renamer#268]
It would be useful to have a native Spanish speaker verify the Spanish translation in app, as it was done just through the json file, I believe.

**Comment by SantiagoJimenezQ** [comment]
Hi, @edwardrowe, I'm a native Spanish speaker. I can check it!

**Comment by edwardrowe** [comment]
That would be great! Just load up the latest version of Mulligan (1.7.3)
either from here or the app store and switch it to Spanish in preferences.
If you find an issue, feel free to change the es.json file directly and
submit a pr! Thanks!
