### ISSUE TITLE
Fix Examples in Preferences to be translation friendly

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-mulligan-renamer#271]
The strings
"This is **sample text** with words **inserted**"
and
"This is **sample text** with words **deleted**"

are broken up into multiple entries that are '+''ed together. This is not correct. It should be
"This is {0} with words {1}."

The challenge is I use these to create a diff preview:  https://github.com/redbluegames/unity-mulligan-renamer/blob/f3612a7ad4d3b13a230e31cad094f9eaa511fc82/Assets/RedBlueGames/MulliganRenamer/Editor/GUI/MulliganUserPreferencesWindow.cs#L235-L239

Instead of assuming where the original string should be broken up and concatenating them, it should instead break up the first string by parsing original string using substring or regex to find the {0} and {1}. It would then reassemble the RenameResult using the broken up string and the string values for the two parameters.

**Comment by CraigBanach** [comment]
I'm investigating this :)

**Comment by edwardrowe** [comment]
Thanks! If you can get #hacktoberfest credit by doing the pr into staging
(and I think you do) that would be appreciated.
