### ISSUE TITLE
Unity 2020.2 Warnings

### ISSUE THREAD

**Issue by justinwasilenko** [redbluegames/unity-mulligan-renamer#274]
When using Unity 2020.2 this warnings will appear:

[CS0618] 'UnityWebRequest.isNetworkError' is obsolete:
'UnityWebRequest.isNetworkError is deprecated. Use (UnityWebRequest.result == UnityWebRequest.Result.ConnectionError) instead.'

[CS0618] 'UnityWebRequest.isHttpError' is obsolete:
'UnityWebRequest.isHttpError is deprecated. Use (UnityWebRequest.result == UnityWebRequest.Result.ProtocolError) instead.'

**Comment by edwardrowe** [comment]
Thanks for the heads up and issue. I've been slacking on getting it updated.

**Comment by edwardrowe** [comment]
Fixed in v1.7.4

Will push to Asset store shortly.
