### ISSUE TITLE
Cannot rename assets containing a dot character

### ISSUE THREAD

**Issue by dorba** [redbluegames/unity-mulligan-renamer#282]
I'm just noting this in case it's something you'd like to modify.

When renaming, the dot character is included in the list of invalid characters, preventing those assets from being renamed. I'm not sure if this restriction existed in previous versions, but 2020 LTS will accept dots in the asset name. 

I was able to fix locally by removing the character from the array here:
https://github.com/redbluegames/unity-mulligan-renamer/blob/main/Assets/RedBlueGames/MulliganRenamer/Editor/Renaming/RenamePreview.cs#L112

**Comment by edwardrowe** [comment]
Thanks for the report - I don't regularly work on the newer versions so
it's really helpful to have people looking out for issues.

I'll get some time to check this one out this weekend hopefully.

Thanks!

**Comment by edwardrowe** [comment]
Thanks again. Should be fixed in Main, though I haven't cut a release for the AssetStore and I don't think I will because it's a pain. If you're using the AssetStore version let me know, and I'll get an updated version out.

**Comment by edwardrowe** [comment]
Release as a .unitypackage is here if you'd like it: https://github.com/redbluegames/unity-mulligan-renamer/releases/tag/v1.7.6
