### ISSUE TITLE
Wiki Missing Screenshots

### ISSUE THREAD

**Issue by mrcarriere** [redbluegames/unity-mulligan-renamer#288]
The wiki, specifically for the [Replace Operations](https://github.com/redbluegames/unity-mulligan-renamer/wiki/Rename-Operations#replace-string), has a bunch of broken image references.

Looking at the source, this looks like the result of renaming the primary branch from "master" => "main".

**Comment by edwardrowe** [comment]
Good catch. Thanks for submitting this issue!

**Comment by edwardrowe** [comment]
Fixed. Thanks!
