### ISSUE TITLE
Renaming Assets to the same name silently rejects rename

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-mulligan-renamer#34]
Repro steps:
1. Select a series of assets in one folder
2. Try to rename them all to the same thing (trim entire string, prefx with "HelloWorld")
3. Press rename
4. Observe only one object is renamed in each directory.

Expectations here are tricky. Maybe we introduce a warning icon next to the previewed objects. Hover over it to see "object cannot be renamed to the previewed value because it would share a name with another asset in the same directory"?

In theory this can happen whether or not you rename all assets to the same thing. It could match an unselected object and not get renamed.

**Comment by lucasrowe** [comment]
The least it should do is warn after like unity does when renaming to a duplicate name. But that preview warning icon sounds pretty good to me in addition. Do you have validation ahead of time of any kind? It seems like you might want the Rename button disabled while there are errors like this that prevent Renaming from working.

**Comment by edwardrowe** [comment]
This is fixed in develop-1.1.0
